### ISSUE TITLE
make post request to server for Login and Signup

### ISSUE THREAD

**Issue by Lyddem** [hrr26-berets/hrr26-berets#86]

**Comment by jacobyoo** [comment]
May I ask what this is for? We already have passport authentication hooked to the front end and login and signup are working as intended.

**Comment by jacobyoo** [comment]
https://github.com/hrr26-berets/hrr26-berets/pull/70

**Comment by jacobyoo** [comment]
Please see: https://github.com/hrr26-berets/hrr26-berets/pull/70

**Comment by jacobyoo** [comment]
Closed per discussion
